steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-central2-docker.pkg.dev/empik-ga360/docker-013/my-build:prod1', '.' ]

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-central2-docker.pkg.dev/empik-ga360/docker-013/my-build:prod1' ]


# Step 3: Deployment to Cloud Run after image is pushed
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'my-service'  # Replace with your service name
  - '--image'
  - 'europe-central2-docker.pkg.dev/empik-ga360/docker-013/my-build:prod1'
  - '--region'
  - 'europe-central2'  # You can change this if you want to deploy to a different region
  - '--platform'
  - 'managed'
  # Optional: if you want to allow unauthenticated access
  - '--allow-unauthenticated'
